### PR TITLE
added Journey to Un'Goro

### PR DESCRIPTION
**Pull request by CookieCompiler**

### CODE REVIEW

**Comment by CookieCompiler** [comment]
Do not merge before release of expansion!

**Comment by judge2020** [comment]
Ok, thanks

**Comment by judge2020** [comment]
Thanks for that, I'm away so won't be able to merge immediately.

**Comment by CookieCompiler** [comment]
Ok, meanwhile I created a release a in my forked repo, so everyone interested can download it there for usage (until it is done here).
[https://github.com/CookieCompiler/Hearthstone-Collection-Tracker/releases/tag/v0.7.1](https://github.com/CookieCompiler/Hearthstone-Collection-Tracker/releases/tag/v0.7.1)

**Comment by adriencarbonne** [comment]
Hello @CookieCompiler , your DLL is throwing an exception:

2017-04-07 16_54_55-hearthstone deck tracker

**Comment by judge2020** [comment]
Testing the dll above would help getting the UnGoro version pushed

**Comment by CookieCompiler** [comment]
Thanks for the information, I've tested the dll before and had no problem with it. I'll have a look at it.

**Comment by judge2020** [comment]
@CookieCompiler see if updating the HearthDb dll fixes it.

Just replace the file in /packages

**Comment by CookieCompiler** [comment]
I replaced the HearthDb.dll and created a new release. Would be nice if you can test it and say me if it works for you. Unfortunately I can't reproduce the error.
https://github.com/CookieCompiler/Hearthstone-Collection-Tracker/releases/tag/v0.7.1-beta

**Comment by LilahLys** [comment]
Still having the exception with the new version.

**Comment by Wyrda65** [comment]
Just tried it out, no exceptions, Un'Goro collection is now shown in tracker. Thanks for update.

**Comment by judge2020** [comment]
If possible please commit the change :)

**Comment by adriencarbonne** [comment]
I got the same exception - BUT I then removed the "CollectionTracker" folder in "C:\Users\[USER]\AppData\Roaming\HearthstoneDeckTracker" and it fixed the issue. Maybe catch the exception and reset the config file?

**Comment by judge2020** [comment]
That can be arranged

**Comment by Pand3m0nia** [comment]
I tried doing what @adriencarbonne did and it worked for me (thanks), except it reset my collection (I'm assuming the previous config files got corrupted with the update?).

**Comment by CookieCompiler** [comment]
@judge2020 I just commited my latest changes.

**Comment by judge2020** [comment]
I'll be adding something to reset config for this release

**Comment by Arakys7** [comment]
I took the code from
https://github.com/CookieCompiler/Hearthstone-Collection-Tracker/releases/tag/v0.7.1-beta

The exception is caused by the Hall of Fame cards still being stored in the Classic Set in Collection_Default.xml in AppData\Roaming\HearthstoneDeckTracker\CollectionTracker, when they've been moved to the Hall of Fame set

To fix it, you can delete the xml file to reset your collection, or do what I did and manually edit the xml file to remove the CardInCollection xml entries for CS2_031, EX1_128, EX1_316, EX1_016, EX1_284, EX1_298

I then added "Hall of Fame" to the CollectableSets list in SetCardsManager.cs and rebuilt the dll

Then, I used the Collection Tracker to set my cards count for the Hall of Fame cards

The proper place to fix it is probably in DataUpdaterV071 to migrate the Hall of Fame cards into their set

**Pull request merged**
